development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rails_test_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rails_test_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
#   variables:
#     sql_mode: TRADITIONAL

production:
  # adapter: postgresql
  encoding: utf8
  reconnect: false
  # database: rails_test_production
  pool: 5
  # username: root
  # password:
  # socket: /tmp/mysql.sock
