# you will need to:
# - add the env var `RAILS_ENV` => `circle` to  CircleCI
# - add config/environments/circle.rb` (copy of `test.rb`)
circle:
  adapter: mysql2
  database: circle_test
  username: ubuntu
  host: localhost

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rails_test_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rails_test_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  # adapter: postgresql
  encoding: utf8
  reconnect: false
  # database: rails_test_production
  pool: 5
  # username: root
  # password:
  # socket: /tmp/mysql.sock
